/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 68
#define LARGE_STATE_COUNT 5
#define SYMBOL_COUNT 77
#define ALIAS_COUNT 0
#define TOKEN_COUNT 48
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 12
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 9
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_forbid = 4,
  anon_sym_warn = 5,
  anon_sym_permit = 6,
  anon_sym_description = 7,
  anon_sym_owner = 8,
  anon_sym_link = 9,
  anon_sym_message = 10,
  anon_sym_unless = 11,
  anon_sym_not = 12,
  anon_sym_or = 13,
  anon_sym_has = 14,
  anon_sym_any = 15,
  anon_sym_all = 16,
  anon_sym_count = 17,
  anon_sym_len = 18,
  anon_sym_lower = 19,
  anon_sym_upper = 20,
  anon_sym_LPAREN = 21,
  anon_sym_RPAREN = 22,
  anon_sym_PLUS = 23,
  anon_sym_DASH = 24,
  anon_sym_STAR = 25,
  anon_sym_SLASH = 26,
  anon_sym_EQ_EQ = 27,
  anon_sym_BANG_EQ = 28,
  anon_sym_LT_EQ = 29,
  anon_sym_GT_EQ = 30,
  anon_sym_LT = 31,
  anon_sym_GT = 32,
  anon_sym_in = 33,
  anon_sym_matches = 34,
  anon_sym_matches_regex = 35,
  anon_sym_contains = 36,
  anon_sym_intersects = 37,
  anon_sym_is_subset = 38,
  anon_sym_DOT = 39,
  anon_sym_LBRACK = 40,
  anon_sym_COMMA = 41,
  anon_sym_RBRACK = 42,
  anon_sym_true = 43,
  anon_sym_false = 44,
  sym_string = 45,
  sym_number = 46,
  sym_comment = 47,
  sym_source_file = 48,
  sym_rule = 49,
  sym_rule_kind = 50,
  sym__rule_clause = 51,
  sym_metadata_clause = 52,
  sym_message_clause = 53,
  sym_unless_clause = 54,
  sym_condition = 55,
  sym_not_condition = 56,
  sym_or_condition = 57,
  sym__simple_condition = 58,
  sym_has_condition = 59,
  sym_quantifier_condition = 60,
  sym_predicate = 61,
  sym_call_expression = 62,
  sym_arithmetic_condition = 63,
  sym__arith_expr = 64,
  sym_binary_expression = 65,
  sym_field_condition = 66,
  sym_cmp_op = 67,
  sym_field_path = 68,
  sym__value = 69,
  sym_list = 70,
  sym_boolean = 71,
  aux_sym_source_file_repeat1 = 72,
  aux_sym_rule_repeat1 = 73,
  aux_sym_or_condition_repeat1 = 74,
  aux_sym_field_path_repeat1 = 75,
  aux_sym_list_repeat1 = 76,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_forbid] = "forbid",
  [anon_sym_warn] = "warn",
  [anon_sym_permit] = "permit",
  [anon_sym_description] = "description",
  [anon_sym_owner] = "owner",
  [anon_sym_link] = "link",
  [anon_sym_message] = "message",
  [anon_sym_unless] = "unless",
  [anon_sym_not] = "not",
  [anon_sym_or] = "or",
  [anon_sym_has] = "has",
  [anon_sym_any] = "any",
  [anon_sym_all] = "all",
  [anon_sym_count] = "count",
  [anon_sym_len] = "len",
  [anon_sym_lower] = "lower",
  [anon_sym_upper] = "upper",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_in] = "in",
  [anon_sym_matches] = "matches",
  [anon_sym_matches_regex] = "matches_regex",
  [anon_sym_contains] = "contains",
  [anon_sym_intersects] = "intersects",
  [anon_sym_is_subset] = "is_subset",
  [anon_sym_DOT] = ".",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_string] = "string",
  [sym_number] = "number",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_rule] = "rule",
  [sym_rule_kind] = "rule_kind",
  [sym__rule_clause] = "_rule_clause",
  [sym_metadata_clause] = "metadata_clause",
  [sym_message_clause] = "message_clause",
  [sym_unless_clause] = "unless_clause",
  [sym_condition] = "condition",
  [sym_not_condition] = "not_condition",
  [sym_or_condition] = "or_condition",
  [sym__simple_condition] = "_simple_condition",
  [sym_has_condition] = "has_condition",
  [sym_quantifier_condition] = "quantifier_condition",
  [sym_predicate] = "predicate",
  [sym_call_expression] = "call_expression",
  [sym_arithmetic_condition] = "arithmetic_condition",
  [sym__arith_expr] = "_arith_expr",
  [sym_binary_expression] = "binary_expression",
  [sym_field_condition] = "field_condition",
  [sym_cmp_op] = "cmp_op",
  [sym_field_path] = "field_path",
  [sym__value] = "_value",
  [sym_list] = "list",
  [sym_boolean] = "boolean",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_rule_repeat1] = "rule_repeat1",
  [aux_sym_or_condition_repeat1] = "or_condition_repeat1",
  [aux_sym_field_path_repeat1] = "field_path_repeat1",
  [aux_sym_list_repeat1] = "list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_forbid] = anon_sym_forbid,
  [anon_sym_warn] = anon_sym_warn,
  [anon_sym_permit] = anon_sym_permit,
  [anon_sym_description] = anon_sym_description,
  [anon_sym_owner] = anon_sym_owner,
  [anon_sym_link] = anon_sym_link,
  [anon_sym_message] = anon_sym_message,
  [anon_sym_unless] = anon_sym_unless,
  [anon_sym_not] = anon_sym_not,
  [anon_sym_or] = anon_sym_or,
  [anon_sym_has] = anon_sym_has,
  [anon_sym_any] = anon_sym_any,
  [anon_sym_all] = anon_sym_all,
  [anon_sym_count] = anon_sym_count,
  [anon_sym_len] = anon_sym_len,
  [anon_sym_lower] = anon_sym_lower,
  [anon_sym_upper] = anon_sym_upper,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_matches] = anon_sym_matches,
  [anon_sym_matches_regex] = anon_sym_matches_regex,
  [anon_sym_contains] = anon_sym_contains,
  [anon_sym_intersects] = anon_sym_intersects,
  [anon_sym_is_subset] = anon_sym_is_subset,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_string] = sym_string,
  [sym_number] = sym_number,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_rule] = sym_rule,
  [sym_rule_kind] = sym_rule_kind,
  [sym__rule_clause] = sym__rule_clause,
  [sym_metadata_clause] = sym_metadata_clause,
  [sym_message_clause] = sym_message_clause,
  [sym_unless_clause] = sym_unless_clause,
  [sym_condition] = sym_condition,
  [sym_not_condition] = sym_not_condition,
  [sym_or_condition] = sym_or_condition,
  [sym__simple_condition] = sym__simple_condition,
  [sym_has_condition] = sym_has_condition,
  [sym_quantifier_condition] = sym_quantifier_condition,
  [sym_predicate] = sym_predicate,
  [sym_call_expression] = sym_call_expression,
  [sym_arithmetic_condition] = sym_arithmetic_condition,
  [sym__arith_expr] = sym__arith_expr,
  [sym_binary_expression] = sym_binary_expression,
  [sym_field_condition] = sym_field_condition,
  [sym_cmp_op] = sym_cmp_op,
  [sym_field_path] = sym_field_path,
  [sym__value] = sym__value,
  [sym_list] = sym_list,
  [sym_boolean] = sym_boolean,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_rule_repeat1] = aux_sym_rule_repeat1,
  [aux_sym_or_condition_repeat1] = aux_sym_or_condition_repeat1,
  [aux_sym_field_path_repeat1] = aux_sym_field_path_repeat1,
  [aux_sym_list_repeat1] = aux_sym_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_forbid] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_warn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_permit] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_description] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_owner] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_link] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_message] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_unless] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_not] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_has] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_any] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_all] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_count] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_len] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_lower] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_upper] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_matches] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_matches_regex] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_contains] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_intersects] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_is_subset] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_rule_kind] = {
    .visible = true,
    .named = true,
  },
  [sym__rule_clause] = {
    .visible = false,
    .named = true,
  },
  [sym_metadata_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_message_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_unless_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_condition] = {
    .visible = true,
    .named = true,
  },
  [sym_not_condition] = {
    .visible = true,
    .named = true,
  },
  [sym_or_condition] = {
    .visible = true,
    .named = true,
  },
  [sym__simple_condition] = {
    .visible = false,
    .named = true,
  },
  [sym_has_condition] = {
    .visible = true,
    .named = true,
  },
  [sym_quantifier_condition] = {
    .visible = true,
    .named = true,
  },
  [sym_predicate] = {
    .visible = true,
    .named = true,
  },
  [sym_call_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_arithmetic_condition] = {
    .visible = true,
    .named = true,
  },
  [sym__arith_expr] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_field_condition] = {
    .visible = true,
    .named = true,
  },
  [sym_cmp_op] = {
    .visible = true,
    .named = true,
  },
  [sym_field_path] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_rule_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_or_condition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_field_path_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_condition = 1,
  field_function = 2,
  field_key = 3,
  field_kind = 4,
  field_lhs = 5,
  field_list = 6,
  field_name = 7,
  field_path = 8,
  field_quantifier = 9,
  field_rhs = 10,
  field_template = 11,
  field_value = 12,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_condition] = "condition",
  [field_function] = "function",
  [field_key] = "key",
  [field_kind] = "kind",
  [field_lhs] = "lhs",
  [field_list] = "list",
  [field_name] = "name",
  [field_path] = "path",
  [field_quantifier] = "quantifier",
  [field_rhs] = "rhs",
  [field_template] = "template",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 1},
  [4] = {.index = 5, .length = 1},
  [5] = {.index = 6, .length = 1},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_kind, 0},
    {field_name, 1},
  [2] =
    {field_key, 0},
    {field_value, 1},
  [4] =
    {field_template, 1},
  [5] =
    {field_condition, 1},
  [6] =
    {field_path, 1},
  [7] =
    {field_list, 1},
    {field_quantifier, 0},
  [9] =
    {field_lhs, 0},
    {field_rhs, 2},
  [11] =
    {field_function, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      ADVANCE_MAP(
        '!', 2,
        '"', 1,
        '#', 29,
        '(', 9,
        ')', 10,
        '*', 13,
        '+', 11,
        ',', 23,
        '-', 12,
        '.', 21,
        '/', 14,
        '<', 19,
        '=', 3,
        '>', 20,
        '[', 22,
        ']', 24,
        '{', 7,
        '}', 8,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(25);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '=') ADVANCE(16);
      END_STATE();
    case 3:
      if (lookahead == '=') ADVANCE(15);
      END_STATE();
    case 4:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 5:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(29);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(17);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(18);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'c', 2,
        'd', 3,
        'f', 4,
        'h', 5,
        'i', 6,
        'l', 7,
        'm', 8,
        'n', 9,
        'o', 10,
        'p', 11,
        't', 12,
        'u', 13,
        'w', 14,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'l') ADVANCE(15);
      if (lookahead == 'n') ADVANCE(16);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 3:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(19);
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(21);
      END_STATE();
    case 6:
      if (lookahead == 'n') ADVANCE(22);
      if (lookahead == 's') ADVANCE(23);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(24);
      if (lookahead == 'i') ADVANCE(25);
      if (lookahead == 'o') ADVANCE(26);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(27);
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 9:
      if (lookahead == 'o') ADVANCE(29);
      END_STATE();
    case 10:
      if (lookahead == 'r') ADVANCE(30);
      if (lookahead == 'w') ADVANCE(31);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 12:
      if (lookahead == 'r') ADVANCE(33);
      END_STATE();
    case 13:
      if (lookahead == 'n') ADVANCE(34);
      if (lookahead == 'p') ADVANCE(35);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(36);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(37);
      END_STATE();
    case 16:
      if (lookahead == 'y') ADVANCE(38);
      END_STATE();
    case 17:
      if (lookahead == 'n') ADVANCE(39);
      if (lookahead == 'u') ADVANCE(40);
      END_STATE();
    case 18:
      if (lookahead == 's') ADVANCE(41);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(42);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(43);
      END_STATE();
    case 21:
      if (lookahead == 's') ADVANCE(44);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_in);
      if (lookahead == 't') ADVANCE(45);
      END_STATE();
    case 23:
      if (lookahead == '_') ADVANCE(46);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(47);
      END_STATE();
    case 25:
      if (lookahead == 'n') ADVANCE(48);
      END_STATE();
    case 26:
      if (lookahead == 'w') ADVANCE(49);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(50);
      END_STATE();
    case 28:
      if (lookahead == 's') ADVANCE(51);
      END_STATE();
    case 29:
      if (lookahead == 't') ADVANCE(52);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 31:
      if (lookahead == 'n') ADVANCE(53);
      END_STATE();
    case 32:
      if (lookahead == 'r') ADVANCE(54);
      END_STATE();
    case 33:
      if (lookahead == 'u') ADVANCE(55);
      END_STATE();
    case 34:
      if (lookahead == 'l') ADVANCE(56);
      END_STATE();
    case 35:
      if (lookahead == 'p') ADVANCE(57);
      END_STATE();
    case 36:
      if (lookahead == 'r') ADVANCE(58);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_all);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_any);
      END_STATE();
    case 39:
      if (lookahead == 't') ADVANCE(59);
      END_STATE();
    case 40:
      if (lookahead == 'n') ADVANCE(60);
      END_STATE();
    case 41:
      if (lookahead == 'c') ADVANCE(61);
      END_STATE();
    case 42:
      if (lookahead == 's') ADVANCE(62);
      END_STATE();
    case 43:
      if (lookahead == 'b') ADVANCE(63);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_has);
      END_STATE();
    case 45:
      if (lookahead == 'e') ADVANCE(64);
      END_STATE();
    case 46:
      if (lookahead == 's') ADVANCE(65);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_len);
      END_STATE();
    case 48:
      if (lookahead == 'k') ADVANCE(66);
      END_STATE();
    case 49:
      if (lookahead == 'e') ADVANCE(67);
      END_STATE();
    case 50:
      if (lookahead == 'c') ADVANCE(68);
      END_STATE();
    case 51:
      if (lookahead == 's') ADVANCE(69);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_not);
      END_STATE();
    case 53:
      if (lookahead == 'e') ADVANCE(70);
      END_STATE();
    case 54:
      if (lookahead == 'm') ADVANCE(71);
      END_STATE();
    case 55:
      if (lookahead == 'e') ADVANCE(72);
      END_STATE();
    case 56:
      if (lookahead == 'e') ADVANCE(73);
      END_STATE();
    case 57:
      if (lookahead == 'e') ADVANCE(74);
      END_STATE();
    case 58:
      if (lookahead == 'n') ADVANCE(75);
      END_STATE();
    case 59:
      if (lookahead == 'a') ADVANCE(76);
      END_STATE();
    case 60:
      if (lookahead == 't') ADVANCE(77);
      END_STATE();
    case 61:
      if (lookahead == 'r') ADVANCE(78);
      END_STATE();
    case 62:
      if (lookahead == 'e') ADVANCE(79);
      END_STATE();
    case 63:
      if (lookahead == 'i') ADVANCE(80);
      END_STATE();
    case 64:
      if (lookahead == 'r') ADVANCE(81);
      END_STATE();
    case 65:
      if (lookahead == 'u') ADVANCE(82);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_link);
      END_STATE();
    case 67:
      if (lookahead == 'r') ADVANCE(83);
      END_STATE();
    case 68:
      if (lookahead == 'h') ADVANCE(84);
      END_STATE();
    case 69:
      if (lookahead == 'a') ADVANCE(85);
      END_STATE();
    case 70:
      if (lookahead == 'r') ADVANCE(86);
      END_STATE();
    case 71:
      if (lookahead == 'i') ADVANCE(87);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 73:
      if (lookahead == 's') ADVANCE(88);
      END_STATE();
    case 74:
      if (lookahead == 'r') ADVANCE(89);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_warn);
      END_STATE();
    case 76:
      if (lookahead == 'i') ADVANCE(90);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_count);
      END_STATE();
    case 78:
      if (lookahead == 'i') ADVANCE(91);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 80:
      if (lookahead == 'd') ADVANCE(92);
      END_STATE();
    case 81:
      if (lookahead == 's') ADVANCE(93);
      END_STATE();
    case 82:
      if (lookahead == 'b') ADVANCE(94);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_lower);
      END_STATE();
    case 84:
      if (lookahead == 'e') ADVANCE(95);
      END_STATE();
    case 85:
      if (lookahead == 'g') ADVANCE(96);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_owner);
      END_STATE();
    case 87:
      if (lookahead == 't') ADVANCE(97);
      END_STATE();
    case 88:
      if (lookahead == 's') ADVANCE(98);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_upper);
      END_STATE();
    case 90:
      if (lookahead == 'n') ADVANCE(99);
      END_STATE();
    case 91:
      if (lookahead == 'p') ADVANCE(100);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_forbid);
      END_STATE();
    case 93:
      if (lookahead == 'e') ADVANCE(101);
      END_STATE();
    case 94:
      if (lookahead == 's') ADVANCE(102);
      END_STATE();
    case 95:
      if (lookahead == 's') ADVANCE(103);
      END_STATE();
    case 96:
      if (lookahead == 'e') ADVANCE(104);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_permit);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_unless);
      END_STATE();
    case 99:
      if (lookahead == 's') ADVANCE(105);
      END_STATE();
    case 100:
      if (lookahead == 't') ADVANCE(106);
      END_STATE();
    case 101:
      if (lookahead == 'c') ADVANCE(107);
      END_STATE();
    case 102:
      if (lookahead == 'e') ADVANCE(108);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_matches);
      if (lookahead == '_') ADVANCE(109);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_message);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_contains);
      END_STATE();
    case 106:
      if (lookahead == 'i') ADVANCE(110);
      END_STATE();
    case 107:
      if (lookahead == 't') ADVANCE(111);
      END_STATE();
    case 108:
      if (lookahead == 't') ADVANCE(112);
      END_STATE();
    case 109:
      if (lookahead == 'r') ADVANCE(113);
      END_STATE();
    case 110:
      if (lookahead == 'o') ADVANCE(114);
      END_STATE();
    case 111:
      if (lookahead == 's') ADVANCE(115);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_is_subset);
      END_STATE();
    case 113:
      if (lookahead == 'e') ADVANCE(116);
      END_STATE();
    case 114:
      if (lookahead == 'n') ADVANCE(117);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_intersects);
      END_STATE();
    case 116:
      if (lookahead == 'g') ADVANCE(118);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(anon_sym_description);
      END_STATE();
    case 118:
      if (lookahead == 'e') ADVANCE(119);
      END_STATE();
    case 119:
      if (lookahead == 'x') ADVANCE(120);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(anon_sym_matches_regex);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_forbid] = ACTIONS(1),
    [anon_sym_warn] = ACTIONS(1),
    [anon_sym_permit] = ACTIONS(1),
    [anon_sym_description] = ACTIONS(1),
    [anon_sym_owner] = ACTIONS(1),
    [anon_sym_link] = ACTIONS(1),
    [anon_sym_message] = ACTIONS(1),
    [anon_sym_unless] = ACTIONS(1),
    [anon_sym_not] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [anon_sym_has] = ACTIONS(1),
    [anon_sym_any] = ACTIONS(1),
    [anon_sym_all] = ACTIONS(1),
    [anon_sym_count] = ACTIONS(1),
    [anon_sym_len] = ACTIONS(1),
    [anon_sym_lower] = ACTIONS(1),
    [anon_sym_upper] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_matches] = ACTIONS(1),
    [anon_sym_matches_regex] = ACTIONS(1),
    [anon_sym_contains] = ACTIONS(1),
    [anon_sym_intersects] = ACTIONS(1),
    [anon_sym_is_subset] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(62),
    [sym_rule] = STATE(48),
    [sym_rule_kind] = STATE(63),
    [aux_sym_source_file_repeat1] = STATE(48),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_forbid] = ACTIONS(7),
    [anon_sym_warn] = ACTIONS(7),
    [anon_sym_permit] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [aux_sym_field_path_repeat1] = STATE(2),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(11),
    [anon_sym_description] = ACTIONS(9),
    [anon_sym_owner] = ACTIONS(9),
    [anon_sym_link] = ACTIONS(9),
    [anon_sym_message] = ACTIONS(9),
    [anon_sym_unless] = ACTIONS(9),
    [anon_sym_not] = ACTIONS(9),
    [anon_sym_or] = ACTIONS(9),
    [anon_sym_has] = ACTIONS(9),
    [anon_sym_any] = ACTIONS(9),
    [anon_sym_all] = ACTIONS(9),
    [anon_sym_count] = ACTIONS(9),
    [anon_sym_len] = ACTIONS(9),
    [anon_sym_lower] = ACTIONS(9),
    [anon_sym_upper] = ACTIONS(9),
    [anon_sym_RPAREN] = ACTIONS(11),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(11),
    [anon_sym_SLASH] = ACTIONS(9),
    [anon_sym_EQ_EQ] = ACTIONS(11),
    [anon_sym_BANG_EQ] = ACTIONS(11),
    [anon_sym_LT_EQ] = ACTIONS(11),
    [anon_sym_GT_EQ] = ACTIONS(11),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(9),
    [anon_sym_in] = ACTIONS(9),
    [anon_sym_matches] = ACTIONS(9),
    [anon_sym_matches_regex] = ACTIONS(9),
    [anon_sym_contains] = ACTIONS(9),
    [anon_sym_intersects] = ACTIONS(9),
    [anon_sym_is_subset] = ACTIONS(9),
    [anon_sym_DOT] = ACTIONS(13),
    [anon_sym_COMMA] = ACTIONS(11),
    [anon_sym_RBRACK] = ACTIONS(11),
    [sym_number] = ACTIONS(11),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [aux_sym_field_path_repeat1] = STATE(4),
    [sym_identifier] = ACTIONS(16),
    [anon_sym_RBRACE] = ACTIONS(18),
    [anon_sym_description] = ACTIONS(16),
    [anon_sym_owner] = ACTIONS(16),
    [anon_sym_link] = ACTIONS(16),
    [anon_sym_message] = ACTIONS(16),
    [anon_sym_unless] = ACTIONS(16),
    [anon_sym_not] = ACTIONS(16),
    [anon_sym_or] = ACTIONS(16),
    [anon_sym_has] = ACTIONS(16),
    [anon_sym_any] = ACTIONS(16),
    [anon_sym_all] = ACTIONS(16),
    [anon_sym_count] = ACTIONS(16),
    [anon_sym_len] = ACTIONS(16),
    [anon_sym_lower] = ACTIONS(16),
    [anon_sym_upper] = ACTIONS(16),
    [anon_sym_RPAREN] = ACTIONS(18),
    [anon_sym_PLUS] = ACTIONS(18),
    [anon_sym_DASH] = ACTIONS(18),
    [anon_sym_STAR] = ACTIONS(18),
    [anon_sym_SLASH] = ACTIONS(16),
    [anon_sym_EQ_EQ] = ACTIONS(18),
    [anon_sym_BANG_EQ] = ACTIONS(18),
    [anon_sym_LT_EQ] = ACTIONS(18),
    [anon_sym_GT_EQ] = ACTIONS(18),
    [anon_sym_LT] = ACTIONS(16),
    [anon_sym_GT] = ACTIONS(16),
    [anon_sym_in] = ACTIONS(16),
    [anon_sym_matches] = ACTIONS(16),
    [anon_sym_matches_regex] = ACTIONS(16),
    [anon_sym_contains] = ACTIONS(16),
    [anon_sym_intersects] = ACTIONS(16),
    [anon_sym_is_subset] = ACTIONS(16),
    [anon_sym_DOT] = ACTIONS(20),
    [anon_sym_COMMA] = ACTIONS(18),
    [anon_sym_RBRACK] = ACTIONS(18),
    [sym_number] = ACTIONS(18),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(4)] = {
    [aux_sym_field_path_repeat1] = STATE(2),
    [sym_identifier] = ACTIONS(22),
    [anon_sym_RBRACE] = ACTIONS(24),
    [anon_sym_description] = ACTIONS(22),
    [anon_sym_owner] = ACTIONS(22),
    [anon_sym_link] = ACTIONS(22),
    [anon_sym_message] = ACTIONS(22),
    [anon_sym_unless] = ACTIONS(22),
    [anon_sym_not] = ACTIONS(22),
    [anon_sym_or] = ACTIONS(22),
    [anon_sym_has] = ACTIONS(22),
    [anon_sym_any] = ACTIONS(22),
    [anon_sym_all] = ACTIONS(22),
    [anon_sym_count] = ACTIONS(22),
    [anon_sym_len] = ACTIONS(22),
    [anon_sym_lower] = ACTIONS(22),
    [anon_sym_upper] = ACTIONS(22),
    [anon_sym_RPAREN] = ACTIONS(24),
    [anon_sym_PLUS] = ACTIONS(24),
    [anon_sym_DASH] = ACTIONS(24),
    [anon_sym_STAR] = ACTIONS(24),
    [anon_sym_SLASH] = ACTIONS(22),
    [anon_sym_EQ_EQ] = ACTIONS(24),
    [anon_sym_BANG_EQ] = ACTIONS(24),
    [anon_sym_LT_EQ] = ACTIONS(24),
    [anon_sym_GT_EQ] = ACTIONS(24),
    [anon_sym_LT] = ACTIONS(22),
    [anon_sym_GT] = ACTIONS(22),
    [anon_sym_in] = ACTIONS(22),
    [anon_sym_matches] = ACTIONS(22),
    [anon_sym_matches_regex] = ACTIONS(22),
    [anon_sym_contains] = ACTIONS(22),
    [anon_sym_intersects] = ACTIONS(22),
    [anon_sym_is_subset] = ACTIONS(22),
    [anon_sym_DOT] = ACTIONS(20),
    [anon_sym_COMMA] = ACTIONS(24),
    [anon_sym_RBRACK] = ACTIONS(24),
    [sym_number] = ACTIONS(24),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 13,
      anon_sym_RBRACE,
      anon_sym_RPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_number,
    ACTIONS(9), 24,
      anon_sym_description,
      anon_sym_owner,
      anon_sym_link,
      anon_sym_message,
      anon_sym_unless,
      anon_sym_not,
      anon_sym_or,
      anon_sym_has,
      anon_sym_any,
      anon_sym_all,
      anon_sym_count,
      anon_sym_len,
      anon_sym_lower,
      anon_sym_upper,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_in,
      anon_sym_matches,
      anon_sym_matches_regex,
      anon_sym_contains,
      anon_sym_intersects,
      anon_sym_is_subset,
      sym_identifier,
  [45] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(26), 1,
      sym_identifier,
    ACTIONS(29), 1,
      anon_sym_RBRACE,
    ACTIONS(34), 1,
      anon_sym_message,
    ACTIONS(37), 1,
      anon_sym_unless,
    ACTIONS(40), 1,
      anon_sym_not,
    ACTIONS(43), 1,
      anon_sym_has,
    ACTIONS(52), 1,
      sym_number,
    STATE(58), 1,
      sym__simple_condition,
    ACTIONS(46), 2,
      anon_sym_any,
      anon_sym_all,
    STATE(23), 2,
      sym_call_expression,
      sym_field_path,
    STATE(24), 2,
      sym__arith_expr,
      sym_binary_expression,
    STATE(31), 2,
      sym_not_condition,
      sym_or_condition,
    ACTIONS(31), 3,
      anon_sym_description,
      anon_sym_owner,
      anon_sym_link,
    ACTIONS(49), 4,
      anon_sym_count,
      anon_sym_len,
      anon_sym_lower,
      anon_sym_upper,
    STATE(28), 4,
      sym_has_condition,
      sym_quantifier_condition,
      sym_arithmetic_condition,
      sym_field_condition,
    STATE(6), 6,
      sym__rule_clause,
      sym_metadata_clause,
      sym_message_clause,
      sym_unless_clause,
      sym_condition,
      aux_sym_rule_repeat1,
  [114] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 9,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_number,
    ACTIONS(55), 24,
      anon_sym_description,
      anon_sym_owner,
      anon_sym_link,
      anon_sym_message,
      anon_sym_unless,
      anon_sym_not,
      anon_sym_or,
      anon_sym_has,
      anon_sym_any,
      anon_sym_all,
      anon_sym_count,
      anon_sym_len,
      anon_sym_lower,
      anon_sym_upper,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_in,
      anon_sym_matches,
      anon_sym_matches_regex,
      anon_sym_contains,
      anon_sym_intersects,
      anon_sym_is_subset,
      sym_identifier,
  [155] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      sym_identifier,
    ACTIONS(61), 1,
      anon_sym_RBRACE,
    ACTIONS(65), 1,
      anon_sym_message,
    ACTIONS(67), 1,
      anon_sym_unless,
    ACTIONS(69), 1,
      anon_sym_not,
    ACTIONS(71), 1,
      anon_sym_has,
    ACTIONS(77), 1,
      sym_number,
    STATE(58), 1,
      sym__simple_condition,
    ACTIONS(73), 2,
      anon_sym_any,
      anon_sym_all,
    STATE(23), 2,
      sym_call_expression,
      sym_field_path,
    STATE(24), 2,
      sym__arith_expr,
      sym_binary_expression,
    STATE(31), 2,
      sym_not_condition,
      sym_or_condition,
    ACTIONS(63), 3,
      anon_sym_description,
      anon_sym_owner,
      anon_sym_link,
    ACTIONS(75), 4,
      anon_sym_count,
      anon_sym_len,
      anon_sym_lower,
      anon_sym_upper,
    STATE(28), 4,
      sym_has_condition,
      sym_quantifier_condition,
      sym_arithmetic_condition,
      sym_field_condition,
    STATE(6), 6,
      sym__rule_clause,
      sym_metadata_clause,
      sym_message_clause,
      sym_unless_clause,
      sym_condition,
      aux_sym_rule_repeat1,
  [224] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(85), 1,
      anon_sym_SLASH,
    ACTIONS(81), 8,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_number,
    ACTIONS(79), 23,
      anon_sym_description,
      anon_sym_owner,
      anon_sym_link,
      anon_sym_message,
      anon_sym_unless,
      anon_sym_not,
      anon_sym_or,
      anon_sym_has,
      anon_sym_any,
      anon_sym_all,
      anon_sym_count,
      anon_sym_len,
      anon_sym_lower,
      anon_sym_upper,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_in,
      anon_sym_matches,
      anon_sym_matches_regex,
      anon_sym_contains,
      anon_sym_intersects,
      anon_sym_is_subset,
      sym_identifier,
  [269] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      sym_identifier,
    ACTIONS(65), 1,
      anon_sym_message,
    ACTIONS(67), 1,
      anon_sym_unless,
    ACTIONS(69), 1,
      anon_sym_not,
    ACTIONS(71), 1,
      anon_sym_has,
    ACTIONS(77), 1,
      sym_number,
    ACTIONS(87), 1,
      anon_sym_RBRACE,
    STATE(58), 1,
      sym__simple_condition,
    ACTIONS(73), 2,
      anon_sym_any,
      anon_sym_all,
    STATE(23), 2,
      sym_call_expression,
      sym_field_path,
    STATE(24), 2,
      sym__arith_expr,
      sym_binary_expression,
    STATE(31), 2,
      sym_not_condition,
      sym_or_condition,
    ACTIONS(63), 3,
      anon_sym_description,
      anon_sym_owner,
      anon_sym_link,
    ACTIONS(75), 4,
      anon_sym_count,
      anon_sym_len,
      anon_sym_lower,
      anon_sym_upper,
    STATE(28), 4,
      sym_has_condition,
      sym_quantifier_condition,
      sym_arithmetic_condition,
      sym_field_condition,
    STATE(8), 6,
      sym__rule_clause,
      sym_metadata_clause,
      sym_message_clause,
      sym_unless_clause,
      sym_condition,
      aux_sym_rule_repeat1,
  [338] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 9,
      anon_sym_RBRACE,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_number,
    ACTIONS(79), 24,
      anon_sym_description,
      anon_sym_owner,
      anon_sym_link,
      anon_sym_message,
      anon_sym_unless,
      anon_sym_not,
      anon_sym_or,
      anon_sym_has,
      anon_sym_any,
      anon_sym_all,
      anon_sym_count,
      anon_sym_len,
      anon_sym_lower,
      anon_sym_upper,
      anon_sym_SLASH,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_in,
      anon_sym_matches,
      anon_sym_matches_regex,
      anon_sym_contains,
      anon_sym_intersects,
      anon_sym_is_subset,
      sym_identifier,
  [379] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      sym_identifier,
    ACTIONS(69), 1,
      anon_sym_not,
    ACTIONS(71), 1,
      anon_sym_has,
    ACTIONS(77), 1,
      sym_number,
    STATE(35), 1,
      sym_condition,
    STATE(58), 1,
      sym__simple_condition,
    ACTIONS(73), 2,
      anon_sym_any,
      anon_sym_all,
    STATE(23), 2,
      sym_call_expression,
      sym_field_path,
    STATE(24), 2,
      sym__arith_expr,
      sym_binary_expression,
    STATE(31), 2,
      sym_not_condition,
      sym_or_condition,
    ACTIONS(75), 4,
      anon_sym_count,
      anon_sym_len,
      anon_sym_lower,
      anon_sym_upper,
    STATE(28), 4,
      sym_has_condition,
      sym_quantifier_condition,
      sym_arithmetic_condition,
      sym_field_condition,
  [429] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      sym_identifier,
    ACTIONS(69), 1,
      anon_sym_not,
    ACTIONS(71), 1,
      anon_sym_has,
    ACTIONS(77), 1,
      sym_number,
    STATE(34), 1,
      sym_condition,
    STATE(58), 1,
      sym__simple_condition,
    ACTIONS(73), 2,
      anon_sym_any,
      anon_sym_all,
    STATE(23), 2,
      sym_call_expression,
      sym_field_path,
    STATE(24), 2,
      sym__arith_expr,
      sym_binary_expression,
    STATE(31), 2,
      sym_not_condition,
      sym_or_condition,
    ACTIONS(75), 4,
      anon_sym_count,
      anon_sym_len,
      anon_sym_lower,
      anon_sym_upper,
    STATE(28), 4,
      sym_has_condition,
      sym_quantifier_condition,
      sym_arithmetic_condition,
      sym_field_condition,
  [479] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(85), 1,
      anon_sym_SLASH,
    ACTIONS(91), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(93), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(89), 15,
      anon_sym_description,
      anon_sym_owner,
      anon_sym_link,
      anon_sym_message,
      anon_sym_unless,
      anon_sym_not,
      anon_sym_or,
      anon_sym_has,
      anon_sym_any,
      anon_sym_all,
      anon_sym_count,
      anon_sym_len,
      anon_sym_lower,
      anon_sym_upper,
      sym_identifier,
  [514] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 4,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_number,
    ACTIONS(95), 15,
      anon_sym_description,
      anon_sym_owner,
      anon_sym_link,
      anon_sym_message,
      anon_sym_unless,
      anon_sym_not,
      anon_sym_or,
      anon_sym_has,
      anon_sym_any,
      anon_sym_all,
      anon_sym_count,
      anon_sym_len,
      anon_sym_lower,
      anon_sym_upper,
      sym_identifier,
  [541] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 4,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_number,
    ACTIONS(99), 15,
      anon_sym_description,
      anon_sym_owner,
      anon_sym_link,
      anon_sym_message,
      anon_sym_unless,
      anon_sym_not,
      anon_sym_or,
      anon_sym_has,
      anon_sym_any,
      anon_sym_all,
      anon_sym_count,
      anon_sym_len,
      anon_sym_lower,
      anon_sym_upper,
      sym_identifier,
  [568] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 4,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_number,
    ACTIONS(103), 15,
      anon_sym_description,
      anon_sym_owner,
      anon_sym_link,
      anon_sym_message,
      anon_sym_unless,
      anon_sym_not,
      anon_sym_or,
      anon_sym_has,
      anon_sym_any,
      anon_sym_all,
      anon_sym_count,
      anon_sym_len,
      anon_sym_lower,
      anon_sym_upper,
      sym_identifier,
  [595] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 4,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_number,
    ACTIONS(107), 15,
      anon_sym_description,
      anon_sym_owner,
      anon_sym_link,
      anon_sym_message,
      anon_sym_unless,
      anon_sym_not,
      anon_sym_or,
      anon_sym_has,
      anon_sym_any,
      anon_sym_all,
      anon_sym_count,
      anon_sym_len,
      anon_sym_lower,
      anon_sym_upper,
      sym_identifier,
  [622] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 4,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_number,
    ACTIONS(111), 15,
      anon_sym_description,
      anon_sym_owner,
      anon_sym_link,
      anon_sym_message,
      anon_sym_unless,
      anon_sym_not,
      anon_sym_or,
      anon_sym_has,
      anon_sym_any,
      anon_sym_all,
      anon_sym_count,
      anon_sym_len,
      anon_sym_lower,
      anon_sym_upper,
      sym_identifier,
  [649] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 1,
      anon_sym_or,
    STATE(20), 1,
      aux_sym_or_condition_repeat1,
    ACTIONS(117), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(115), 14,
      anon_sym_description,
      anon_sym_owner,
      anon_sym_link,
      anon_sym_message,
      anon_sym_unless,
      anon_sym_not,
      anon_sym_has,
      anon_sym_any,
      anon_sym_all,
      anon_sym_count,
      anon_sym_len,
      anon_sym_lower,
      anon_sym_upper,
      sym_identifier,
  [679] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      sym_identifier,
    ACTIONS(71), 1,
      anon_sym_has,
    ACTIONS(77), 1,
      sym_number,
    ACTIONS(73), 2,
      anon_sym_any,
      anon_sym_all,
    STATE(23), 2,
      sym_call_expression,
      sym_field_path,
    STATE(24), 2,
      sym__arith_expr,
      sym_binary_expression,
    ACTIONS(75), 4,
      anon_sym_count,
      anon_sym_len,
      anon_sym_lower,
      anon_sym_upper,
    STATE(30), 5,
      sym__simple_condition,
      sym_has_condition,
      sym_quantifier_condition,
      sym_arithmetic_condition,
      sym_field_condition,
  [717] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 1,
      anon_sym_or,
    STATE(20), 1,
      aux_sym_or_condition_repeat1,
    ACTIONS(124), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(122), 14,
      anon_sym_description,
      anon_sym_owner,
      anon_sym_link,
      anon_sym_message,
      anon_sym_unless,
      anon_sym_not,
      anon_sym_has,
      anon_sym_any,
      anon_sym_all,
      anon_sym_count,
      anon_sym_len,
      anon_sym_lower,
      anon_sym_upper,
      sym_identifier,
  [747] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_SLASH,
    STATE(42), 1,
      sym_cmp_op,
    ACTIONS(128), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
    ACTIONS(134), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_in,
      anon_sym_matches,
    ACTIONS(132), 8,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_matches_regex,
      anon_sym_contains,
      anon_sym_intersects,
      anon_sym_is_subset,
  [778] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(85), 1,
      anon_sym_SLASH,
    STATE(40), 1,
      sym_cmp_op,
    ACTIONS(93), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(134), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_in,
      anon_sym_matches,
    ACTIONS(132), 8,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_matches_regex,
      anon_sym_contains,
      anon_sym_intersects,
      anon_sym_is_subset,
  [811] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(136), 15,
      anon_sym_description,
      anon_sym_owner,
      anon_sym_link,
      anon_sym_message,
      anon_sym_unless,
      anon_sym_not,
      anon_sym_or,
      anon_sym_has,
      anon_sym_any,
      anon_sym_all,
      anon_sym_count,
      anon_sym_len,
      anon_sym_lower,
      anon_sym_upper,
      sym_identifier,
  [836] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(140), 15,
      anon_sym_description,
      anon_sym_owner,
      anon_sym_link,
      anon_sym_message,
      anon_sym_unless,
      anon_sym_not,
      anon_sym_or,
      anon_sym_has,
      anon_sym_any,
      anon_sym_all,
      anon_sym_count,
      anon_sym_len,
      anon_sym_lower,
      anon_sym_upper,
      sym_identifier,
  [861] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(144), 15,
      anon_sym_description,
      anon_sym_owner,
      anon_sym_link,
      anon_sym_message,
      anon_sym_unless,
      anon_sym_not,
      anon_sym_or,
      anon_sym_has,
      anon_sym_any,
      anon_sym_all,
      anon_sym_count,
      anon_sym_len,
      anon_sym_lower,
      anon_sym_upper,
      sym_identifier,
  [886] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      anon_sym_or,
    ACTIONS(150), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(148), 14,
      anon_sym_description,
      anon_sym_owner,
      anon_sym_link,
      anon_sym_message,
      anon_sym_unless,
      anon_sym_not,
      anon_sym_has,
      anon_sym_any,
      anon_sym_all,
      anon_sym_count,
      anon_sym_len,
      anon_sym_lower,
      anon_sym_upper,
      sym_identifier,
  [913] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(154), 15,
      anon_sym_description,
      anon_sym_owner,
      anon_sym_link,
      anon_sym_message,
      anon_sym_unless,
      anon_sym_not,
      anon_sym_or,
      anon_sym_has,
      anon_sym_any,
      anon_sym_all,
      anon_sym_count,
      anon_sym_len,
      anon_sym_lower,
      anon_sym_upper,
      sym_identifier,
  [938] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(115), 15,
      anon_sym_description,
      anon_sym_owner,
      anon_sym_link,
      anon_sym_message,
      anon_sym_unless,
      anon_sym_not,
      anon_sym_or,
      anon_sym_has,
      anon_sym_any,
      anon_sym_all,
      anon_sym_count,
      anon_sym_len,
      anon_sym_lower,
      anon_sym_upper,
      sym_identifier,
  [963] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(148), 14,
      anon_sym_description,
      anon_sym_owner,
      anon_sym_link,
      anon_sym_message,
      anon_sym_unless,
      anon_sym_not,
      anon_sym_has,
      anon_sym_any,
      anon_sym_all,
      anon_sym_count,
      anon_sym_len,
      anon_sym_lower,
      anon_sym_upper,
      sym_identifier,
  [987] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(158), 14,
      anon_sym_description,
      anon_sym_owner,
      anon_sym_link,
      anon_sym_message,
      anon_sym_unless,
      anon_sym_not,
      anon_sym_has,
      anon_sym_any,
      anon_sym_all,
      anon_sym_count,
      anon_sym_len,
      anon_sym_lower,
      anon_sym_upper,
      sym_identifier,
  [1011] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(162), 14,
      anon_sym_description,
      anon_sym_owner,
      anon_sym_link,
      anon_sym_message,
      anon_sym_unless,
      anon_sym_not,
      anon_sym_has,
      anon_sym_any,
      anon_sym_all,
      anon_sym_count,
      anon_sym_len,
      anon_sym_lower,
      anon_sym_upper,
      sym_identifier,
  [1035] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(166), 14,
      anon_sym_description,
      anon_sym_owner,
      anon_sym_link,
      anon_sym_message,
      anon_sym_unless,
      anon_sym_not,
      anon_sym_has,
      anon_sym_any,
      anon_sym_all,
      anon_sym_count,
      anon_sym_len,
      anon_sym_lower,
      anon_sym_upper,
      sym_identifier,
  [1059] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 2,
      anon_sym_RBRACE,
      sym_number,
    ACTIONS(170), 14,
      anon_sym_description,
      anon_sym_owner,
      anon_sym_link,
      anon_sym_message,
      anon_sym_unless,
      anon_sym_not,
      anon_sym_has,
      anon_sym_any,
      anon_sym_all,
      anon_sym_count,
      anon_sym_len,
      anon_sym_lower,
      anon_sym_upper,
      sym_identifier,
  [1083] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(25), 1,
      sym_predicate,
    STATE(41), 1,
      sym_cmp_op,
    ACTIONS(134), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_in,
      anon_sym_matches,
    ACTIONS(132), 8,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_matches_regex,
      anon_sym_contains,
      anon_sym_intersects,
      anon_sym_is_subset,
  [1109] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      sym_identifier,
    ACTIONS(174), 1,
      anon_sym_LBRACK,
    ACTIONS(176), 1,
      anon_sym_RBRACK,
    ACTIONS(178), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(180), 2,
      sym_string,
      sym_number,
    STATE(52), 4,
      sym_field_path,
      sym__value,
      sym_list,
      sym_boolean,
  [1136] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      sym_identifier,
    ACTIONS(174), 1,
      anon_sym_LBRACK,
    ACTIONS(182), 1,
      anon_sym_RBRACK,
    ACTIONS(178), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(184), 2,
      sym_string,
      sym_number,
    STATE(57), 4,
      sym_field_path,
      sym__value,
      sym_list,
      sym_boolean,
  [1163] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      sym_identifier,
    ACTIONS(174), 1,
      anon_sym_LBRACK,
    ACTIONS(186), 1,
      anon_sym_RBRACK,
    ACTIONS(178), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(184), 2,
      sym_string,
      sym_number,
    STATE(57), 4,
      sym_field_path,
      sym__value,
      sym_list,
      sym_boolean,
  [1190] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      sym_identifier,
    ACTIONS(188), 1,
      sym_number,
    ACTIONS(75), 4,
      anon_sym_count,
      anon_sym_len,
      anon_sym_lower,
      anon_sym_upper,
    STATE(14), 4,
      sym_call_expression,
      sym__arith_expr,
      sym_binary_expression,
      sym_field_path,
  [1212] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      sym_identifier,
    ACTIONS(174), 1,
      anon_sym_LBRACK,
    ACTIONS(178), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(190), 2,
      sym_string,
      sym_number,
    STATE(27), 4,
      sym_field_path,
      sym__value,
      sym_list,
      sym_boolean,
  [1236] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      sym_identifier,
    ACTIONS(174), 1,
      anon_sym_LBRACK,
    ACTIONS(178), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(192), 2,
      sym_string,
      sym_number,
    STATE(26), 4,
      sym_field_path,
      sym__value,
      sym_list,
      sym_boolean,
  [1260] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      sym_identifier,
    ACTIONS(194), 1,
      sym_number,
    ACTIONS(75), 4,
      anon_sym_count,
      anon_sym_len,
      anon_sym_lower,
      anon_sym_upper,
    STATE(9), 4,
      sym_call_expression,
      sym__arith_expr,
      sym_binary_expression,
      sym_field_path,
  [1282] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 3,
      anon_sym_LBRACK,
      sym_string,
      sym_number,
    ACTIONS(196), 7,
      anon_sym_count,
      anon_sym_len,
      anon_sym_lower,
      anon_sym_upper,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [1300] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      sym_identifier,
    ACTIONS(200), 1,
      sym_number,
    ACTIONS(75), 4,
      anon_sym_count,
      anon_sym_len,
      anon_sym_lower,
      anon_sym_upper,
    STATE(11), 4,
      sym_call_expression,
      sym__arith_expr,
      sym_binary_expression,
      sym_field_path,
  [1322] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 1,
      sym_identifier,
    ACTIONS(174), 1,
      anon_sym_LBRACK,
    ACTIONS(178), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(184), 2,
      sym_string,
      sym_number,
    STATE(57), 4,
      sym_field_path,
      sym__value,
      sym_list,
      sym_boolean,
  [1346] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 1,
      ts_builtin_sym_end,
    STATE(63), 1,
      sym_rule_kind,
    STATE(47), 2,
      sym_rule,
      aux_sym_source_file_repeat1,
    ACTIONS(204), 3,
      anon_sym_forbid,
      anon_sym_warn,
      anon_sym_permit,
  [1365] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 1,
      ts_builtin_sym_end,
    STATE(63), 1,
      sym_rule_kind,
    STATE(47), 2,
      sym_rule,
      aux_sym_source_file_repeat1,
    ACTIONS(7), 3,
      anon_sym_forbid,
      anon_sym_warn,
      anon_sym_permit,
  [1384] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 4,
      ts_builtin_sym_end,
      anon_sym_forbid,
      anon_sym_warn,
      anon_sym_permit,
  [1394] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(211), 4,
      ts_builtin_sym_end,
      anon_sym_forbid,
      anon_sym_warn,
      anon_sym_permit,
  [1404] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      anon_sym_RBRACK,
    ACTIONS(213), 1,
      anon_sym_COMMA,
    STATE(53), 1,
      aux_sym_list_repeat1,
  [1417] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(215), 1,
      anon_sym_COMMA,
    ACTIONS(217), 1,
      anon_sym_RBRACK,
    STATE(51), 1,
      aux_sym_list_repeat1,
  [1430] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      anon_sym_COMMA,
    ACTIONS(222), 1,
      anon_sym_RBRACK,
    STATE(53), 1,
      aux_sym_list_repeat1,
  [1443] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      sym_identifier,
    STATE(60), 1,
      sym_field_path,
  [1453] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      sym_identifier,
    STATE(29), 1,
      sym_field_path,
  [1463] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      sym_identifier,
    STATE(36), 1,
      sym_field_path,
  [1473] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1481] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      anon_sym_or,
    STATE(22), 1,
      aux_sym_or_condition_repeat1,
  [1491] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 1,
      sym_string,
  [1498] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      anon_sym_RPAREN,
  [1505] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      sym_string,
  [1512] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      ts_builtin_sym_end,
  [1519] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      sym_string,
  [1526] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      anon_sym_LPAREN,
  [1533] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      sym_string,
  [1540] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 1,
      sym_identifier,
  [1547] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      anon_sym_LBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(5)] = 0,
  [SMALL_STATE(6)] = 45,
  [SMALL_STATE(7)] = 114,
  [SMALL_STATE(8)] = 155,
  [SMALL_STATE(9)] = 224,
  [SMALL_STATE(10)] = 269,
  [SMALL_STATE(11)] = 338,
  [SMALL_STATE(12)] = 379,
  [SMALL_STATE(13)] = 429,
  [SMALL_STATE(14)] = 479,
  [SMALL_STATE(15)] = 514,
  [SMALL_STATE(16)] = 541,
  [SMALL_STATE(17)] = 568,
  [SMALL_STATE(18)] = 595,
  [SMALL_STATE(19)] = 622,
  [SMALL_STATE(20)] = 649,
  [SMALL_STATE(21)] = 679,
  [SMALL_STATE(22)] = 717,
  [SMALL_STATE(23)] = 747,
  [SMALL_STATE(24)] = 778,
  [SMALL_STATE(25)] = 811,
  [SMALL_STATE(26)] = 836,
  [SMALL_STATE(27)] = 861,
  [SMALL_STATE(28)] = 886,
  [SMALL_STATE(29)] = 913,
  [SMALL_STATE(30)] = 938,
  [SMALL_STATE(31)] = 963,
  [SMALL_STATE(32)] = 987,
  [SMALL_STATE(33)] = 1011,
  [SMALL_STATE(34)] = 1035,
  [SMALL_STATE(35)] = 1059,
  [SMALL_STATE(36)] = 1083,
  [SMALL_STATE(37)] = 1109,
  [SMALL_STATE(38)] = 1136,
  [SMALL_STATE(39)] = 1163,
  [SMALL_STATE(40)] = 1190,
  [SMALL_STATE(41)] = 1212,
  [SMALL_STATE(42)] = 1236,
  [SMALL_STATE(43)] = 1260,
  [SMALL_STATE(44)] = 1282,
  [SMALL_STATE(45)] = 1300,
  [SMALL_STATE(46)] = 1322,
  [SMALL_STATE(47)] = 1346,
  [SMALL_STATE(48)] = 1365,
  [SMALL_STATE(49)] = 1384,
  [SMALL_STATE(50)] = 1394,
  [SMALL_STATE(51)] = 1404,
  [SMALL_STATE(52)] = 1417,
  [SMALL_STATE(53)] = 1430,
  [SMALL_STATE(54)] = 1443,
  [SMALL_STATE(55)] = 1453,
  [SMALL_STATE(56)] = 1463,
  [SMALL_STATE(57)] = 1473,
  [SMALL_STATE(58)] = 1481,
  [SMALL_STATE(59)] = 1491,
  [SMALL_STATE(60)] = 1498,
  [SMALL_STATE(61)] = 1505,
  [SMALL_STATE(62)] = 1512,
  [SMALL_STATE(63)] = 1519,
  [SMALL_STATE(64)] = 1526,
  [SMALL_STATE(65)] = 1533,
  [SMALL_STATE(66)] = 1540,
  [SMALL_STATE(67)] = 1547,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [9] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_field_path_repeat1, 2, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_field_path_repeat1, 2, 0, 0),
  [13] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_field_path_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [16] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field_path, 1, 0, 0),
  [18] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_path, 1, 0, 0),
  [20] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [22] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field_path, 2, 0, 0),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_path, 2, 0, 0),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_rule_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_rule_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_rule_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_rule_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_rule_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_rule_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_rule_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_rule_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_rule_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_rule_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_expression, 4, 0, 8),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 4, 0, 8),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arithmetic_condition, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arithmetic_condition, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 5, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 5, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 4, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_or_condition_repeat1, 2, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_or_condition_repeat1, 2, 0, 0),
  [119] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_or_condition_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_or_condition, 2, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_or_condition, 2, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__arith_expr, 1, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__arith_expr, 1, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [134] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quantifier_condition, 3, 0, 6),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quantifier_condition, 3, 0, 6),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field_condition, 3, 0, 7),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_condition, 3, 0, 7),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_predicate, 2, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_predicate, 2, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_condition, 1, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 1, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__simple_condition, 1, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_has_condition, 2, 0, 5),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_has_condition, 2, 0, 5),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_metadata_clause, 2, 0, 2),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_metadata_clause, 2, 0, 2),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_message_clause, 2, 0, 3),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_clause, 2, 0, 3),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_not_condition, 2, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_not_condition, 2, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unless_clause, 2, 0, 4),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unless_clause, 2, 0, 4),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cmp_op, 1, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cmp_op, 1, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [204] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 4, 0, 1),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 5, 0, 1),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [219] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule_kind, 1, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [234] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_crowdcontrol(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
